// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// keep_mat
arma::mat keep_mat(arma::mat& X, arma::vec keep);
RcppExport SEXP edsProjection_keep_mat(SEXP XSEXP, SEXP keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type keep(keepSEXP);
    __result = Rcpp::wrap(keep_mat(X, keep));
    return __result;
END_RCPP
}
// pcd_scaling
arma::mat pcd_scaling(arma::mat& X);
RcppExport SEXP edsProjection_pcd_scaling(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    __result = Rcpp::wrap(pcd_scaling(X));
    return __result;
END_RCPP
}
// eds_keep
arma::vec eds_keep(arma::mat& X_norm, arma::vec& eps);
RcppExport SEXP edsProjection_eds_keep(SEXP X_normSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X_norm(X_normSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type eps(epsSEXP);
    __result = Rcpp::wrap(eds_keep(X_norm, eps));
    return __result;
END_RCPP
}
// p_eps
arma::mat p_eps(arma::mat& X, arma::vec& eps);
RcppExport SEXP edsProjection_p_eps(SEXP XSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type eps(epsSEXP);
    __result = Rcpp::wrap(p_eps(X, eps));
    return __result;
END_RCPP
}
// p_eps_const
arma::mat p_eps_const(arma::mat& X, double eps);
RcppExport SEXP edsProjection_p_eps_const(SEXP XSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    __result = Rcpp::wrap(p_eps_const(X, eps));
    return __result;
END_RCPP
}
// normal_kernel_density
arma::vec normal_kernel_density(arma::mat& X, double h);
RcppExport SEXP edsProjection_normal_kernel_density(SEXP XSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    __result = Rcpp::wrap(normal_kernel_density(X, h));
    return __result;
END_RCPP
}
// almost_ergodic_indices
arma::vec almost_ergodic_indices(arma::mat& X, double delta, double h);
RcppExport SEXP edsProjection_almost_ergodic_indices(SEXP XSEXP, SEXP deltaSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    __result = Rcpp::wrap(almost_ergodic_indices(X, delta, h));
    return __result;
END_RCPP
}
// almost_ergodic
arma::mat almost_ergodic(arma::mat& X, double delta, double h);
RcppExport SEXP edsProjection_almost_ergodic(SEXP XSEXP, SEXP deltaSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    __result = Rcpp::wrap(almost_ergodic(X, delta, h));
    return __result;
END_RCPP
}
// p_eps_cheap
arma::mat p_eps_cheap(arma::mat& X, arma::vec& eps, double delta, double h);
RcppExport SEXP edsProjection_p_eps_cheap(SEXP XSEXP, SEXP epsSEXP, SEXP deltaSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    __result = Rcpp::wrap(p_eps_cheap(X, eps, delta, h));
    return __result;
END_RCPP
}
// p_eps_cheap_const
arma::mat p_eps_cheap_const(arma::mat& X, double eps, double delta, double h);
RcppExport SEXP edsProjection_p_eps_cheap_const(SEXP XSEXP, SEXP epsSEXP, SEXP deltaSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    __result = Rcpp::wrap(p_eps_cheap_const(X, eps, delta, h));
    return __result;
END_RCPP
}
// integrand_ngm
double integrand_ngm(arma::mat exog, arma::mat endog, arma::rowvec exog_lead, List params, arma::mat coeffs, int n_exog, int n_endog, int N, arma::rowvec upper, arma::rowvec lower, bool cheby);
RcppExport SEXP edsProjection_integrand_ngm(SEXP exogSEXP, SEXP endogSEXP, SEXP exog_leadSEXP, SEXP paramsSEXP, SEXP coeffsSEXP, SEXP n_exogSEXP, SEXP n_endogSEXP, SEXP NSEXP, SEXP upperSEXP, SEXP lowerSEXP, SEXP chebySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type endog(endogSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type exog_lead(exog_leadSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< int >::type n_exog(n_exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_endog(n_endogSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< bool >::type cheby(chebySEXP);
    __result = Rcpp::wrap(integrand_ngm(exog, endog, exog_lead, params, coeffs, n_exog, n_endog, N, upper, lower, cheby));
    return __result;
END_RCPP
}
// err_ngm_mc
double err_ngm_mc(arma::mat exog, arma::mat endog, arma::mat exog_innov, List params, arma::mat coeffs, int n_exog, int n_endog, arma::rowvec rho, arma::rowvec sig_eps, int n_mc, int N, arma::rowvec upper, arma::rowvec lower, bool cheby);
RcppExport SEXP edsProjection_err_ngm_mc(SEXP exogSEXP, SEXP endogSEXP, SEXP exog_innovSEXP, SEXP paramsSEXP, SEXP coeffsSEXP, SEXP n_exogSEXP, SEXP n_endogSEXP, SEXP rhoSEXP, SEXP sig_epsSEXP, SEXP n_mcSEXP, SEXP NSEXP, SEXP upperSEXP, SEXP lowerSEXP, SEXP chebySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type endog(endogSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type exog_innov(exog_innovSEXP);
    Rcpp::traits::input_parameter< List >::type params(paramsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< int >::type n_exog(n_exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_endog(n_endogSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type sig_eps(sig_epsSEXP);
    Rcpp::traits::input_parameter< int >::type n_mc(n_mcSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< bool >::type cheby(chebySEXP);
    __result = Rcpp::wrap(err_ngm_mc(exog, endog, exog_innov, params, coeffs, n_exog, n_endog, rho, sig_eps, n_mc, N, upper, lower, cheby));
    return __result;
END_RCPP
}
// idx_increment
arma::urowvec idx_increment(arma::urowvec idx, int N, int K);
RcppExport SEXP edsProjection_idx_increment(SEXP idxSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::urowvec >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(idx_increment(idx, N, K));
    return __result;
END_RCPP
}
// idx_count
int idx_count(int N, int K);
RcppExport SEXP edsProjection_idx_count(SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(idx_count(N, K));
    return __result;
END_RCPP
}
// idx_create
arma::umat idx_create(int N, int K);
RcppExport SEXP edsProjection_idx_create(SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(idx_create(N, K));
    return __result;
END_RCPP
}
// ordinary_create
arma::mat ordinary_create(arma::rowvec x, int N, int K);
RcppExport SEXP edsProjection_ordinary_create(SEXP xSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::rowvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(ordinary_create(x, N, K));
    return __result;
END_RCPP
}
// cheby_create
arma::mat cheby_create(arma::rowvec x, int N, int K);
RcppExport SEXP edsProjection_cheby_create(SEXP xSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::rowvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(cheby_create(x, N, K));
    return __result;
END_RCPP
}
// basis_cube
arma::cube basis_cube(arma::mat X, int N, int K, bool cheby);
RcppExport SEXP edsProjection_basis_cube(SEXP XSEXP, SEXP NSEXP, SEXP KSEXP, SEXP chebySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type cheby(chebySEXP);
    __result = Rcpp::wrap(basis_cube(X, N, K, cheby));
    return __result;
END_RCPP
}
// X_rescale
arma::mat X_rescale(arma::mat X_in, int K, bool pc_rescale);
RcppExport SEXP edsProjection_X_rescale(SEXP X_inSEXP, SEXP KSEXP, SEXP pc_rescaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X_in(X_inSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type pc_rescale(pc_rescaleSEXP);
    __result = Rcpp::wrap(X_rescale(X_in, K, pc_rescale));
    return __result;
END_RCPP
}
// X_limits
arma::mat X_limits(arma::mat X_in, arma::rowvec lower, arma::rowvec upper, int M, int K);
RcppExport SEXP edsProjection_X_limits(SEXP X_inSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP MSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X_in(X_inSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(X_limits(X_in, lower, upper, M, K));
    return __result;
END_RCPP
}
// poly_eval
arma::vec poly_eval(arma::vec a, arma::mat X_in, int N, arma::rowvec lower, arma::rowvec upper, bool cheby);
RcppExport SEXP edsProjection_poly_eval(SEXP aSEXP, SEXP X_inSEXP, SEXP NSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP chebySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_in(X_inSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< bool >::type cheby(chebySEXP);
    __result = Rcpp::wrap(poly_eval(a, X_in, N, lower, upper, cheby));
    return __result;
END_RCPP
}
// ar1_sim
arma::vec ar1_sim(int n_pds, double rho, double sig_eps, bool init_flag, double init);
RcppExport SEXP edsProjection_ar1_sim(SEXP n_pdsSEXP, SEXP rhoSEXP, SEXP sig_epsSEXP, SEXP init_flagSEXP, SEXP initSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n_pds(n_pdsSEXP);
    Rcpp::traits::input_parameter< double >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< double >::type sig_eps(sig_epsSEXP);
    Rcpp::traits::input_parameter< bool >::type init_flag(init_flagSEXP);
    Rcpp::traits::input_parameter< double >::type init(initSEXP);
    __result = Rcpp::wrap(ar1_sim(n_pds, rho, sig_eps, init_flag, init));
    return __result;
END_RCPP
}
// endog_update
arma::rowvec endog_update(arma::rowvec exog, arma::rowvec endog_old, arma::mat coeffs, int n_exog, int n_endog, int N, arma::rowvec upper, arma::rowvec lower, bool cheby);
RcppExport SEXP edsProjection_endog_update(SEXP exogSEXP, SEXP endog_oldSEXP, SEXP coeffsSEXP, SEXP n_exogSEXP, SEXP n_endogSEXP, SEXP NSEXP, SEXP upperSEXP, SEXP lowerSEXP, SEXP chebySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::rowvec >::type exog(exogSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type endog_old(endog_oldSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< int >::type n_exog(n_exogSEXP);
    Rcpp::traits::input_parameter< int >::type n_endog(n_endogSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< bool >::type cheby(chebySEXP);
    __result = Rcpp::wrap(endog_update(exog, endog_old, coeffs, n_exog, n_endog, N, upper, lower, cheby));
    return __result;
END_RCPP
}
// endog_sim
arma::mat endog_sim(int n_out, arma::mat exog_sim, arma::mat coeffs, int N, arma::rowvec upper, arma::rowvec lower, arma::rowvec endog_init, bool cheby, int kappa, int burn);
RcppExport SEXP edsProjection_endog_sim(SEXP n_outSEXP, SEXP exog_simSEXP, SEXP coeffsSEXP, SEXP NSEXP, SEXP upperSEXP, SEXP lowerSEXP, SEXP endog_initSEXP, SEXP chebySEXP, SEXP kappaSEXP, SEXP burnSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type n_out(n_outSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type exog_sim(exog_simSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type endog_init(endog_initSEXP);
    Rcpp::traits::input_parameter< bool >::type cheby(chebySEXP);
    Rcpp::traits::input_parameter< int >::type kappa(kappaSEXP);
    Rcpp::traits::input_parameter< int >::type burn(burnSEXP);
    __result = Rcpp::wrap(endog_sim(n_out, exog_sim, coeffs, N, upper, lower, endog_init, cheby, kappa, burn));
    return __result;
END_RCPP
}
// irf_create
arma::mat irf_create(int pds, int n_sim, int N, int shk_idx, arma::rowvec rho, arma::rowvec sig_eps, arma::mat coeffs, arma::rowvec upper, arma::rowvec lower, arma::rowvec init, int n_endog, int n_exog, double shk, bool cheby);
RcppExport SEXP edsProjection_irf_create(SEXP pdsSEXP, SEXP n_simSEXP, SEXP NSEXP, SEXP shk_idxSEXP, SEXP rhoSEXP, SEXP sig_epsSEXP, SEXP coeffsSEXP, SEXP upperSEXP, SEXP lowerSEXP, SEXP initSEXP, SEXP n_endogSEXP, SEXP n_exogSEXP, SEXP shkSEXP, SEXP chebySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type pds(pdsSEXP);
    Rcpp::traits::input_parameter< int >::type n_sim(n_simSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type shk_idx(shk_idxSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type rho(rhoSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type sig_eps(sig_epsSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type coeffs(coeffsSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type init(initSEXP);
    Rcpp::traits::input_parameter< int >::type n_endog(n_endogSEXP);
    Rcpp::traits::input_parameter< int >::type n_exog(n_exogSEXP);
    Rcpp::traits::input_parameter< double >::type shk(shkSEXP);
    Rcpp::traits::input_parameter< bool >::type cheby(chebySEXP);
    __result = Rcpp::wrap(irf_create(pds, n_sim, N, shk_idx, rho, sig_eps, coeffs, upper, lower, init, n_endog, n_exog, shk, cheby));
    return __result;
END_RCPP
}
