// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// keep_mat
arma::mat keep_mat(arma::mat& X, arma::vec keep);
RcppExport SEXP edsProjection_keep_mat(SEXP XSEXP, SEXP keepSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec >::type keep(keepSEXP);
    __result = Rcpp::wrap(keep_mat(X, keep));
    return __result;
END_RCPP
}
// pcd_scaling
arma::mat pcd_scaling(arma::mat& X);
RcppExport SEXP edsProjection_pcd_scaling(SEXP XSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    __result = Rcpp::wrap(pcd_scaling(X));
    return __result;
END_RCPP
}
// eds_keep
arma::vec eds_keep(arma::mat& X_norm, arma::vec& eps);
RcppExport SEXP edsProjection_eds_keep(SEXP X_normSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X_norm(X_normSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type eps(epsSEXP);
    __result = Rcpp::wrap(eds_keep(X_norm, eps));
    return __result;
END_RCPP
}
// p_eps
arma::mat p_eps(arma::mat& X, arma::vec& eps);
RcppExport SEXP edsProjection_p_eps(SEXP XSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type eps(epsSEXP);
    __result = Rcpp::wrap(p_eps(X, eps));
    return __result;
END_RCPP
}
// p_eps_const
arma::mat p_eps_const(arma::mat& X, double eps);
RcppExport SEXP edsProjection_p_eps_const(SEXP XSEXP, SEXP epsSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    __result = Rcpp::wrap(p_eps_const(X, eps));
    return __result;
END_RCPP
}
// normal_kernel_density
arma::vec normal_kernel_density(arma::mat& X, double h);
RcppExport SEXP edsProjection_normal_kernel_density(SEXP XSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    __result = Rcpp::wrap(normal_kernel_density(X, h));
    return __result;
END_RCPP
}
// almost_ergodic_indices
arma::vec almost_ergodic_indices(arma::mat& X, double delta, double h);
RcppExport SEXP edsProjection_almost_ergodic_indices(SEXP XSEXP, SEXP deltaSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    __result = Rcpp::wrap(almost_ergodic_indices(X, delta, h));
    return __result;
END_RCPP
}
// almost_ergodic
arma::mat almost_ergodic(arma::mat& X, double delta, double h);
RcppExport SEXP edsProjection_almost_ergodic(SEXP XSEXP, SEXP deltaSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    __result = Rcpp::wrap(almost_ergodic(X, delta, h));
    return __result;
END_RCPP
}
// p_eps_cheap
arma::mat p_eps_cheap(arma::mat& X, arma::vec& eps, double delta, double h);
RcppExport SEXP edsProjection_p_eps_cheap(SEXP XSEXP, SEXP epsSEXP, SEXP deltaSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< arma::vec& >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    __result = Rcpp::wrap(p_eps_cheap(X, eps, delta, h));
    return __result;
END_RCPP
}
// p_eps_cheap_const
arma::mat p_eps_cheap_const(arma::mat& X, double eps, double delta, double h);
RcppExport SEXP edsProjection_p_eps_cheap_const(SEXP XSEXP, SEXP epsSEXP, SEXP deltaSEXP, SEXP hSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat& >::type X(XSEXP);
    Rcpp::traits::input_parameter< double >::type eps(epsSEXP);
    Rcpp::traits::input_parameter< double >::type delta(deltaSEXP);
    Rcpp::traits::input_parameter< double >::type h(hSEXP);
    __result = Rcpp::wrap(p_eps_cheap_const(X, eps, delta, h));
    return __result;
END_RCPP
}
// idx_increment
arma::urowvec idx_increment(arma::urowvec idx, int N, int K);
RcppExport SEXP edsProjection_idx_increment(SEXP idxSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::urowvec >::type idx(idxSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(idx_increment(idx, N, K));
    return __result;
END_RCPP
}
// idx_count
int idx_count(int N, int K);
RcppExport SEXP edsProjection_idx_count(SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(idx_count(N, K));
    return __result;
END_RCPP
}
// idx_create
arma::umat idx_create(int N, int K);
RcppExport SEXP edsProjection_idx_create(SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(idx_create(N, K));
    return __result;
END_RCPP
}
// ordinary_create
arma::mat ordinary_create(arma::rowvec x, int N, int K);
RcppExport SEXP edsProjection_ordinary_create(SEXP xSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::rowvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(ordinary_create(x, N, K));
    return __result;
END_RCPP
}
// cheby_create
arma::mat cheby_create(arma::rowvec x, int N, int K);
RcppExport SEXP edsProjection_cheby_create(SEXP xSEXP, SEXP NSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::rowvec >::type x(xSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(cheby_create(x, N, K));
    return __result;
END_RCPP
}
// basis_cube
arma::cube basis_cube(arma::mat X, int N, int K, bool cheby);
RcppExport SEXP edsProjection_basis_cube(SEXP XSEXP, SEXP NSEXP, SEXP KSEXP, SEXP chebySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X(XSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type cheby(chebySEXP);
    __result = Rcpp::wrap(basis_cube(X, N, K, cheby));
    return __result;
END_RCPP
}
// X_rescale
arma::mat X_rescale(arma::mat X_in, int K, bool pc_rescale);
RcppExport SEXP edsProjection_X_rescale(SEXP X_inSEXP, SEXP KSEXP, SEXP pc_rescaleSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X_in(X_inSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    Rcpp::traits::input_parameter< bool >::type pc_rescale(pc_rescaleSEXP);
    __result = Rcpp::wrap(X_rescale(X_in, K, pc_rescale));
    return __result;
END_RCPP
}
// X_limits
arma::mat X_limits(arma::mat X_in, arma::rowvec lower, arma::rowvec upper, int M, int K);
RcppExport SEXP edsProjection_X_limits(SEXP X_inSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP MSEXP, SEXP KSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::mat >::type X_in(X_inSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< int >::type M(MSEXP);
    Rcpp::traits::input_parameter< int >::type K(KSEXP);
    __result = Rcpp::wrap(X_limits(X_in, lower, upper, M, K));
    return __result;
END_RCPP
}
// poly_eval
arma::vec poly_eval(arma::vec a, arma::mat X_in, int N, arma::rowvec lower, arma::rowvec upper, bool cheby);
RcppExport SEXP edsProjection_poly_eval(SEXP aSEXP, SEXP X_inSEXP, SEXP NSEXP, SEXP lowerSEXP, SEXP upperSEXP, SEXP chebySEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< arma::vec >::type a(aSEXP);
    Rcpp::traits::input_parameter< arma::mat >::type X_in(X_inSEXP);
    Rcpp::traits::input_parameter< int >::type N(NSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type lower(lowerSEXP);
    Rcpp::traits::input_parameter< arma::rowvec >::type upper(upperSEXP);
    Rcpp::traits::input_parameter< bool >::type cheby(chebySEXP);
    __result = Rcpp::wrap(poly_eval(a, X_in, N, lower, upper, cheby));
    return __result;
END_RCPP
}
