# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

keep_mat <- function(X, keep) {
    .Call('edsProjection_keep_mat', PACKAGE = 'edsProjection', X, keep)
}

pcd_scaling <- function(X) {
    .Call('edsProjection_pcd_scaling', PACKAGE = 'edsProjection', X)
}

p_eps <- function(X, eps) {
    .Call('edsProjection_p_eps', PACKAGE = 'edsProjection', X, eps)
}

p_eps_const <- function(X, eps) {
    .Call('edsProjection_p_eps_const', PACKAGE = 'edsProjection', X, eps)
}

normal_kernel_density <- function(X, h = 0) {
    .Call('edsProjection_normal_kernel_density', PACKAGE = 'edsProjection', X, h)
}

almost_ergodic <- function(X, delta, h = 0) {
    .Call('edsProjection_almost_ergodic', PACKAGE = 'edsProjection', X, delta, h)
}

