# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

keep_mat <- function(X, keep) {
    .Call('edsProjection_keep_mat', PACKAGE = 'edsProjection', X, keep)
}

pcd_scaling <- function(X) {
    .Call('edsProjection_pcd_scaling', PACKAGE = 'edsProjection', X)
}

eds_keep <- function(X_norm, eps) {
    .Call('edsProjection_eds_keep', PACKAGE = 'edsProjection', X_norm, eps)
}

p_eps <- function(X, eps) {
    .Call('edsProjection_p_eps', PACKAGE = 'edsProjection', X, eps)
}

p_eps_const <- function(X, eps) {
    .Call('edsProjection_p_eps_const', PACKAGE = 'edsProjection', X, eps)
}

normal_kernel_density <- function(X, h = 0) {
    .Call('edsProjection_normal_kernel_density', PACKAGE = 'edsProjection', X, h)
}

almost_ergodic_indices <- function(X, delta, h = 0) {
    .Call('edsProjection_almost_ergodic_indices', PACKAGE = 'edsProjection', X, delta, h)
}

almost_ergodic <- function(X, delta, h = 0) {
    .Call('edsProjection_almost_ergodic', PACKAGE = 'edsProjection', X, delta, h)
}

p_eps_cheap <- function(X, eps, delta, h = 0) {
    .Call('edsProjection_p_eps_cheap', PACKAGE = 'edsProjection', X, eps, delta, h)
}

p_eps_cheap_const <- function(X, eps, delta, h = 0) {
    .Call('edsProjection_p_eps_cheap_const', PACKAGE = 'edsProjection', X, eps, delta, h)
}

idx_increment <- function(idx, N, K) {
    .Call('edsProjection_idx_increment', PACKAGE = 'edsProjection', idx, N, K)
}

idx_count <- function(N, K) {
    .Call('edsProjection_idx_count', PACKAGE = 'edsProjection', N, K)
}

idx_create <- function(N, K) {
    .Call('edsProjection_idx_create', PACKAGE = 'edsProjection', N, K)
}

ordinary_create <- function(x, N, K) {
    .Call('edsProjection_ordinary_create', PACKAGE = 'edsProjection', x, N, K)
}

cheby_create <- function(x, N, K) {
    .Call('edsProjection_cheby_create', PACKAGE = 'edsProjection', x, N, K)
}

basis_cube <- function(X, N, K, cheby = FALSE) {
    .Call('edsProjection_basis_cube', PACKAGE = 'edsProjection', X, N, K, cheby)
}

X_rescale <- function(X_in, K, pc_rescale = FALSE) {
    .Call('edsProjection_X_rescale', PACKAGE = 'edsProjection', X_in, K, pc_rescale)
}

X_limits <- function(X_in, lower, upper, M, K) {
    .Call('edsProjection_X_limits', PACKAGE = 'edsProjection', X_in, lower, upper, M, K)
}

poly_eval <- function(a, X_in, N, lower, upper, cheby = FALSE) {
    .Call('edsProjection_poly_eval', PACKAGE = 'edsProjection', a, X_in, N, lower, upper, cheby)
}

ar1_sim <- function(n_pds, rho, sig_eps, init_flag = FALSE, init = 0) {
    .Call('edsProjection_ar1_sim', PACKAGE = 'edsProjection', n_pds, rho, sig_eps, init_flag, init)
}

endog_update <- function(exog, endog_old, coeffs, n_exog, n_endog, N, upper, lower, cheby = FALSE) {
    .Call('edsProjection_endog_update', PACKAGE = 'edsProjection', exog, endog_old, coeffs, n_exog, n_endog, N, upper, lower, cheby)
}

endog_sim <- function(n_out, exog_sim, coeffs, N, upper, lower, endog_init, cheby = FALSE, kappa = 1L, burn = 0L) {
    .Call('edsProjection_endog_sim', PACKAGE = 'edsProjection', n_out, exog_sim, coeffs, N, upper, lower, endog_init, cheby, kappa, burn)
}

